# Generated by Django 4.2.25 on 2025-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='cert_type',
            field=models.CharField(choices=[('conduct', 'Conduct'), ('residence', 'Residence Recognition'), ('community', 'Community Engagement'), ('Storen Computer', 'Storen Computer'), ('other', 'Other')], max_length=20),
        ),
    ]
