# Generated by Django 4.2.25 on 2025-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='cert_type',
            field=models.CharField(choices=[('conduct', 'Conduct'), ('residence', 'Residence Recognition'), ('community', 'Community Engagement'), ('Stolen Computer', 'Stolen Computer'), ('other', 'Other')], max_length=20),
        ),
    ]
