# Generated by Django 4.2.25 on 2025-11-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImport',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
