# Generated by Django 4.2.25 on 2025-11-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_locationimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='cell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='location_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='province',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='village',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='cert_type',
            field=models.CharField(choices=[('conduct', 'Conduct'), ('residence', 'Residence Recognition'), ('community', 'Community Engagement'), ('stolen_computer', 'Stolen Computer'), ('other', 'Other')], max_length=20),
        ),
    ]
