# Generated by Django 4.2.25 on 2025-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificaterequest_cert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='email',
            field=models.EmailField(default='umudugudu@gmail.com', max_length=254),
        ),
    ]
