# Generated by Django 4.2.25 on 2025-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificaterequest_cell_certificaterequest_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StolenLaptopCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=16)),
                ('stolen_datetime', models.DateTimeField()),
                ('location', models.TextField()),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet')], max_length=20)),
                ('brand', models.CharField(choices=[('Lenovo', 'Lenovo'), ('HP', 'HP'), ('Dell', 'Dell'), ('Mac', 'Mac')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('intel_core', models.CharField(choices=[('i3', 'Intel Core i3'), ('i5', 'Intel Core i5'), ('i7', 'Intel Core i7')], max_length=10)),
                ('ram', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB')], max_length=10)),
                ('storage', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'Hard Disk')], max_length=10)),
                ('witness_1_name', models.CharField(max_length=100)),
                ('witness_1_phone', models.CharField(max_length=15)),
                ('witness_2_name', models.CharField(max_length=100)),
                ('witness_2_phone', models.CharField(max_length=15)),
                ('witness_3_name', models.CharField(max_length=100)),
                ('witness_3_phone', models.CharField(max_length=15)),
                ('reported_to_police', models.BooleanField(default=False)),
                ('other_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
