# Generated by Django 4.2.25 on 2026-09-03 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_stolenlaptopcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isibo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('isibo_leader', 'Isibo Leader'), ('village_leader', 'Village Leader'), ('cell_leader', 'Cell Leader'), ('sector_leader', 'Sector Leader'), ('security_volunteer', 'Security Volunteer'), ('cleaning_volunteer', 'Cleaning Service Volunteer'), ('system_admin', 'System Admin')], default='citizen', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='village',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Village Approval'), ('village_approved', 'Pending Cell Approval'), ('cell_approved', 'Pending Sector Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('cleaning', 'Cleaning Service'), ('security', 'Security Service')], max_length=20)),
                ('trimester', models.IntegerField(choices=[(1, 'Trimester 1'), (2, 'Trimester 2'), (3, 'Trimester 3')])),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('citizen', 'service', 'trimester', 'year')},
            },
        ),
    ]
