# Generated by Django 4.2.25 on 2026-09-03 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_customuser_cell_customuser_district_customuser_isibo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepayment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=16)),
                ('age', models.PositiveIntegerField()),
                ('village', models.IntegerField()),
                ('isibo', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='citizen_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_tmp', to='certificates.citizen'),
        ),
    ]
