# Generated by Django 4.2.25 on 2026-09-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_servicepayment_point_at_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
