# Generated by Django 4.2.25 on 2026-09-16 12:11

import certificates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_citizen_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='generated_document',
            field=models.FileField(blank=True, null=True, upload_to='generated/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='cert_type',
            field=models.CharField(choices=[('conduct', 'Certificate of Conduct'), ('residence', 'Residence Recognition'), ('community', 'Community Engagement Referral'), ('stolen_computer', 'Stolen Laptop / Electronic Device Report'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Village Leader Review'), ('village_approved', 'Pending Cell Approval'), ('cell_approved', 'Pending Sector Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('national_id', 'National ID / Passport'), ('student_card', 'Student Card'), ('proof', 'Proof / Supporting Document'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=certificates.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='certificates.certificaterequest')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('umuganda', 'Community Work (Umuganda)'), ('meeting', 'Meeting / Gathering'), ('general', 'General Announcement')], default='umuganda', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda')], default='en', max_length=2)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('letter_date', models.DateField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, default='', max_length=30)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('gathering_point', models.CharField(blank=True, default='', max_length=200)),
                ('partner', models.CharField(blank=True, default='', max_length=200)),
                ('audience', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-letter_date', '-created_at'],
            },
        ),
    ]
