# Generated by Django 4.2.25 on 2026-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_certificaterequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='meeting_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
