# Generated by Django 4.2.25 on 2026-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_announcement_meeting_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='location_details',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='announcement',
            name='reminder',
            field=models.TextField(blank=True, default=''),
        ),
    ]
