# Generated by Django 4.2.25 on 2026-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_announcement_location_details_announcement_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='activities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
