# Generated by Django 4.2.25 on 2026-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_announcement_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='generated_document',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
