# Generated by Django 4.2.25 on 2026-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_certificaterequest_verification_code_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='code_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='endorsements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Village Leader Review'), ('village_approved', 'Approved by Village · awaiting Cell'), ('cell_approved', 'Approved by Cell · awaiting Sector'), ('approved', 'Fully Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
